# Generated by Django 2.2.12 on 2020-06-23 14:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import exam.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField(default=None, max_length=200)),
                ('code', models.TextField(blank=True)),
                ('A', models.CharField(max_length=100)),
                ('B', models.CharField(max_length=100)),
                ('C', models.CharField(max_length=100)),
                ('D', models.CharField(max_length=100)),
                ('Type', models.CharField(choices=[('1', 'Aptitude'), ('2', 'C'), ('3', 'Java'), ('4', 'BigData'), ('5', 'Algo')], default='1', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('test_code', models.IntegerField(default=exam.models.testCode, primary_key=True, serialize=False, unique=True)),
                ('start_time', models.DateTimeField(default=exam.models.now_plus_10)),
                ('duration', models.PositiveIntegerField(default=30)),
                ('corr_score', models.PositiveIntegerField(default=4, verbose_name='Score for correct ans')),
                ('wrong_score', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(0)], verbose_name='Score for wrong ans')),
                ('examinees', models.ManyToManyField(blank=True, related_name='tests', to='student.Profile')),
                ('questions', models.ManyToManyField(related_name='questions', to='exam.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_code', models.IntegerField()),
                ('score', models.IntegerField(default=0)),
                ('Q1', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q2', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q3', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q4', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q5', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q6', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q7', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q8', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q9', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q10', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q11', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q12', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q13', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q14', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q15', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q16', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q17', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q18', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q19', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q20', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q21', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q22', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q23', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q24', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q25', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q26', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q27', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q28', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q29', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q30', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q31', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q32', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q33', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q34', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q35', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q36', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q37', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q38', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q39', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q40', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q41', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q42', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q43', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q44', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q45', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q46', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q47', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q48', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q49', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('Q50', models.CharField(blank=True, choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1, null=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='student.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans', models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], default='1', max_length=1)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='exam.Question')),
            ],
        ),
    ]
