# Generated by Django 2.2.12 on 2020-06-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='algo1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='algo2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='algo3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='response',
            name='algo4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='ans',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], max_length=1),
        ),
        migrations.AlterField(
            model_name='question',
            name='statement',
            field=models.TextField(default=None),
        ),
    ]
